// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetResume() {
  return window['go']['main']['App']['GetResume']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function LoadFileFromPath(arg1) {
  return window['go']['main']['App']['LoadFileFromPath'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveNative(arg1) {
  return window['go']['main']['App']['SaveNative'](arg1);
}

export function SavePDF(arg1) {
  return window['go']['main']['App']['SavePDF'](arg1);
}

export function SavePDFToPath(arg1, arg2) {
  return window['go']['main']['App']['SavePDFToPath'](arg1, arg2);
}

export function SaveResumeFile() {
  return window['go']['main']['App']['SaveResumeFile']();
}

export function UpdateResume(arg1) {
  return window['go']['main']['App']['UpdateResume'](arg1);
}
